Fix build on MacOS-X 10.14: missing Xerces include dir
This undoes most of the Xerces related part of the commits listed below.
The issue resolved here is that the Xerces include dir *is* set in the
CMakeLists.txt of src/Base, but it got removed from various App and Gui
dirs in src/Mod. If those now include a header from src/Base, which
itself includes xercesc, the build fails using Apple clang version 11.0.0
(clang-1100.0.33.17) on Mojave, configured using cmake 3.22.1, with
errors like the following:

In file included from .../src/Mod/Part/App/FeaturePartBoolean.cpp:34:
In file included from .../src/App/Application.h:33:
.../src/Base/Parameter.h:54:10: fatal error: 'xercesc/util/XercesDefs.hpp' file not found
 #include <xercesc/util/XercesDefs.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Finally, a full list of the commits that introduced this spurious include
dir optimization for reference:
- Drawing: commit e6113e07123e72dbd7d6bcd6dfbae4d11e33dc79
- Image: commit d4673eb681f60bc261fbecadcfad86ef99058353
- Import: commit 3862a2222529afc31f1011aa72d656e79d21fd7f
- Inspection: commit fe79498327e1a79d0fe74c39ea79e98dc6ef8ac9
- Mesh: commit d11d93a5a914766bfe850980be85f5386995894c
- Part: commit f0b055c905bb9f588ef456591df9100d8cd593f1
- PartDesign: commit 87761c66325d6a0325e3e55a2570781f447205e0
- Path: commit 1b7516f3b3ea33b8fd25d7e9a594dbd6e7d587e0
- Points: commit 4a62fb9611ce3a50b8ae87c97b1129d7dedd33cc
- Raytracing: commit 2868865ed5b8bb242005c21ca2d49b63be3ba830
- ReverseEnginering: commit 9afa952b52047f22e2e33e99cc4e73ecc7b10c68
- Robot: commit 476b1aaeeda40d7687eda0e5e8a9ed425bcbb4d6
- Sketcher: commit cc121513eac11501d6b3cb74188ce9499be76b4a
- Spreadsheet: commit 6d86f90810e13ec7ebca8512ede10ab44e5bc40
- Start: commit 58511debdcc6e91f07711ee857b99e0cc719f355
- Surface: commit d65c69487a7d3f214f5e3f2011b2a380d60dfb29
- TechDraw: commit 26946e60532e97cbd601640ecbe408b0ef52e86d
- Test: commit 1c40effb6ba9a7005aa3f5aff55ac508dd60a3d8
- Web: commit ed51109e485fe832a3909dc85b6853055b6206fb